### PR TITLE
Correctly parse string boolean for ai param

### PR DESCRIPTION
**Pull request by chrisamirani**
### Summary
The `ai` argument on the `TranspilerService` was not honoured.

### Details and comments
The `TranspilerService` class has an argument `ai` which is defined to be a Boolean, however it actually needs to be a `'true' or 'false'`. I have defined the condition to properly map the boolean to string.

Note: I was not sure if we need 'auto' as an option at all since technically it was never used. If that's actually useful, maybe we can change the type to string or an enum?

### CODE REVIEW

**Comment by victor-villar** [comment]
Hi @chrisamirani ! Thanks a lot for the contribution and for being our first community contributor! 

Regarding the PR itself, we do really need the `auto` option, as it is one of the accepted values by the API: https://docs.quantum.ibm.com/api/qiskit-transpiler-service-rest/tags/transpiler-methods#tags__transpiler-methods__operations__transpile_transpile_post.

Could you change it to accept that value as well, using an enum, for example, as you mention in your `comments` section?

**Comment by chrisamirani** [comment]
Hey @victor-villar . Done! I'll be running the test now. Though it would be great if you can validate the tests yourself too. Hopefully CI pipeline will be added soon? 🤞

**Comment by chrisamirani** [comment]
@victor-villar All tests passed except those that require authentication for the IBM service. So I think it'd be great if you verified. I also noticed that my linter introduced some style changes on the README file. Maybe it'd be good to also add some linting rules?

**Review by cbjuan — COMMENTED** [review]
Hi @chrisamirani. As Victor said, thanks for being the 1st community PR!

Regarding the pipeline, we're on it in #6, so for your next PR it should be ready :) 

As of the markdown file, you're right, we should add some linting guidelines and rules. For this PR I'd prefer to only cover in the markdown file the changes in terms of strings (true, false, auto) you added and not include the style changes. In any case these changes are not a blocker for me.

Let us run the tests with your changes and our IBM Quantum authentication tokens so we can double check everything. Apart from that, the code changes look OK, so thanks!

**Review by victor-villar — APPROVED** [review]
LGTM!
I've run all tests successfully!

**Review by cbjuan — APPROVED** [review]
Tests passed, approving.

Thanks @chrisamirani !

**Pull request merged**
